### ISSUE TITLE
Make it easier for editors to edit forms

### ISSUE THREAD

**Issue by keelanfh** [localgovdrupal/localgov_forms#35]
On a fresh install of localgov_forms, it's somewhat surprising to content editors that they can't edit them like other content. A lot of the discussion around web forms was that this would enable content designers to create web forms, so it's surprising that the default setup requires a developer to create the forms.

* Councils generally use Config ignore to exclude webforms from config - could we require it here and have some default configuration to do this?
* Can we then also modify the editor role to allow them to edit webforms?

This feels to me like a more sensible default and would save councils development costs for creating web forms and/or configuring the setup to allow content designers to do this.

**Comment by willguv** [comment]
Copying @Adnan-cds who might have done this, or have a view

**Comment by andybroomfield** [comment]
[Config ignore](https://drupal.org/project/config_ignore) if you want a way of doing this via the UI.
Or there is the same tecnique that directories uses, though I would like that behind an option as there are some forms we do actully commit and version control.

Worth noting at BHCC we have a seperate role for webforms as its mostly a different team building them, though defaulting to editor may be a good start.

**Comment by Adnan-cds** [comment]
As Andy has said, the config_ignore module saves you from undoing form changes made by editors.

Please note that localgov_forms is a module and not an install profile.  It doesn't setup a Drupal site with all the necessary configurations for a decent Webform site.  It only provides [custom Webform elements](https://github.com/localgovdrupal/localgov_forms#additional-components).  Perhaps the module name is a bit misleading.

**Comment by keelanfh** [comment]
We're using it on our own site, not a separate forms site - so I wouldn't expect an install profile, but rather just thinking that including the config_ignore module could be a useful addition to this module, especially if it's already being used by the councils that use this.

**Comment by andybroomfield** [comment]
[This is how directories does it](https://github.com/localgovdrupal/localgov_directories/blob/2.x/src/EventSubscriber/DirectoriesConfigSubscriber.php), if we want to bundle it with the module.

In terms of this module vs an install profile. It depends on if we want this module to provide elements or if we want to use to to provide an out the box set up. It should be noted that #34 raised that this module does overwrite existing webform settings.

**Comment by Adnan-cds** [comment]
Ah, I wasn't aware of #34.  I thought I have got rid of the [bit](https://github.com/localgovdrupal/localgov_forms/blob/1.x/config/install/localgov_forms.webform.settings.yml) that overrides side-wide webform configuration.  Are you people okay if I delete [localgov_forms_install()](https://github.com/localgovdrupal/localgov_forms/blob/9876f55b8460ad9b56af59de9adc34ae5f8252e1/localgov_forms.install#L11) now?  This module has been about webform elements up to this point, so shouldn't be touching site-wide webform settings.

As for individual webforms, it's up to site admins how they want to manage webforms.  Here at Croydon, webforms are entirely in the hands of editors.  They even import the YAMLs from the content staging site to the live site.  Automated config imports don't touch webforms.  But it is possible there would be sites where webforms configs would be entirely exported/imported by automated config export/import.  That's why I am not keen for this module to meddle with webform configs.

**Comment by andybroomfield** [comment]
Yeah, we've patched it to deal with that problem, I think we can remove it.
I'd be happy keeping this as elements, though we should post either something in the readme, or a post installation message about webform config so devs can set up the site to ignore webform config entities using either the core config_exclude or adding the following to config_ignore
````
webform.webform.*
webform.webform_options.*
````

**Comment by willguv** [comment]
@andybroomfield could you add the above messages to readme as that makes the issue and the fix obvious for now

We can discuss other changes at a later meeting

Thanks

**Comment by andybroomfield** [comment]
@willguv added a how to to the readme in #39. 
If that is approved I'll close this issue and make a new issue for including some default config ignore.
[Preview it here!](https://github.com/localgovdrupal/localgov_forms/blob/fix/1.x-35-config-ignore-readme/README.md)
